#!/bin/bash

# seconds to live
export TIME_TO_LIVE=28

# Temperature is halved after generation of FORWARD_TEMP_JUMP routes.
export FORWARD_TEMP_JUMP=1000000
# Processing stops when temperature reaches 300, so the initial temperature gives how long to process.
export FORWARD_INITIAL_TEMPERATURE=10000000
# The "day to regrow route from" is drawn from a negative binomial distribution with
# FORWARD_PARAM_SUCCESSES sucesses and FORWARD_PARAM_SUCCESS_PR prob. of success.
export FORWARD_PARAM_SUCCESSES=2
export FORWARD_PARAM_SUCCESS_PR=0.3
export FORWARD_ZERO_TEMP=10

export BACKWARDS_TEMP_JUMP=1000000
export BACKWARDS_INITIAL_TEMPERATURE=10000000
export BACKWARDS_PARAM_SUCCESSES=2
export BACKWARDS_PARAM_SUCCESS_PR=0.3
export BACKWARDS_ZERO_TEMP=10

# export BACKWARDS_TEMP_JUMP=1000000
# export BACKWARDS_INITIAL_TEMPERATURE=10000
# export BACKWARDS_PARAM_SUCCESSES=2
# export BACKWARDS_PARAM_SUCCESS_PR=0.1
# export BACKWARDS_ZERO_TEMP=10

INPUT_FILE=data_20.txt

# ./production-forward-nearest-sa $INPUT_FILE
# ./production-backwards-nearest-sa $INPUT_FILE
# export DEBUG=1

./ts-thread $INPUT_FILE
